spring:
  datasource:
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: 
    database-platform: 
    database: 
    show-sql: 
 
 data:
    mongodb:
      database: 
      username:
      password:

